
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 19 13:30:37 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALSTO = 45;
  public static final int PLUSPLUS = 23;
  public static final int CHAR = 49;
  public static final int CONST = 24;
  public static final int CASE = 43;
  public static final int LPAREN = 6;
  public static final int GREATER = 28;
  public static final int SEMI = 5;
  public static final int CONTINUE = 34;
  public static final int LESS = 26;
  public static final int MINUS = 19;
  public static final int RPAREN = 7;
  public static final int AND = 25;
  public static final int OR = 36;
  public static final int BOOL = 46;
  public static final int ELESS = 33;
  public static final int COMMA = 8;
  public static final int CLASS = 32;
  public static final int DIV = 18;
  public static final int DOUBLEDOT = 14;
  public static final int DIFFERENT = 29;
  public static final int PLUS = 11;
  public static final int IF = 50;
  public static final int LSQBRACE = 35;
  public static final int DOT = 17;
  public static final int RSWBREACE = 20;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 21;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int MUL = 41;
  public static final int NUMBER = 47;
  public static final int MOD = 40;
  public static final int EGREATER = 38;
  public static final int IDENT = 48;
  public static final int BREAK = 42;
  public static final int VOID = 13;
  public static final int SWITCH = 22;
  public static final int ELSE = 51;
  public static final int LBRACE = 3;
  public static final int ENUM = 39;
  public static final int READ = 27;
  public static final int WHILE = 30;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int QUESTION = 44;
  public static final int RSQBRACE = 37;
  public static final int PRINT = 9;
  public static final int DO = 31;
}

